apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-app
  namespace: argocd
spec:
  project: sandbox-test
  sources:
    - repoURL: https://charts.bitnami.com/bitnami
      chart: nginx
      targetRevision: 19.0.0
      helm:
        valueFiles:
          - $values/nginx/values.yaml
    - repoURL: 'https://github.com/yyjj-kim/sandbox-test.git'
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: infra-nginx  # 실제 앱이 설치될 네임스페이스
  syncPolicy:
    automated:
      prune: true
